name: hello world flow

on: [push]

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Step 1
        run: echo "hello world!"

  job_two:
    runs-on: ubuntu-latest
    needs: job_one
    steps:
      - name: Step 2
        run: echo "job_two runs after job_one!" 